version: '3.8'

services:
  web:
    build: .
    container_name: nunjucks_web_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
